In [1]:
# OpenAginface Embbedding(e5I Embedding: https://colab.research.google.com/drive/1kAlp6UBL4gruOFu6P81oyyFDKm-Q1pjP?usp=sharing
# Hug): https://colab.research.google.com/drive/1leBfCovUHnwaXUaQbR8WD04S9X5TOXkB?usp=sharing

In [2]:
!pip install -U sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-3.2.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.44.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.5.0+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.5.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.24.7)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (10.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.19.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)
Downloading sentence_transformers-3.2.1-py3-none-any.whl (255 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.8/255.8 kB 2.7 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-3.2.1

In [3]:
from sentence_transformers import SentenceTransformer

import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [4]:
model = SentenceTransformer('intfloat/multilingual-e5-large')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/160k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

In [5]:
def get_embedding(text):
  return list(model.encode(text))

In [6]:
text = "저는 배가 고파요"

In [7]:
embedding_result = get_embedding(text)
print(embedding_result)

[0.04318022, -0.009389596, -0.029974656, -0.021847721, 0.008802254, -0.012031631, -0.018495135, 0.06704781, 0.028791418, -0.03948399, 0.02987866, -0.008794932, -0.08429655, -0.027926527, -0.02685578, -0.025287356, -0.020104185, 0.022588367, 0.016430035, -0.0020965182, 0.017649721, -0.00017739319, -0.028981823, -0.035869177, -0.004513344, -0.024690658, -0.022577252, -0.024434766, -0.023427267, -0.045547653, -0.001628101, -0.008928311, -0.05860899, -0.06786314, -0.014932926, 0.020689417, 0.037066013, 0.044556297, -0.009612499, 0.031444214, -0.020827698, 0.03944552, -0.008022598, -0.015470755, -0.03503493, 0.009510037, 0.040413916, 0.01642659, -0.0044270335, 0.046948776, 0.026334152, -0.00013101123, 0.0052588843, -0.032404754, -0.045209937, 0.035994858, -0.019932441, -0.00076589733, -0.03470194, 0.00074088905, -0.015383591, 0.01743607, 0.022885554, -0.0056656892, -0.045858167, 0.05478112, 0.04131082, 0.008394142, -0.057727873, 0.026928134, -0.030992936, 0.011734557, -0.014550493, -0.042979572, -0.019200789, -0.005571923, 0.026179262, -0.029727673, 0.01007347, -0.033213742, 0.08396921, -0.0006630012, 0.023234976, -0.032689024, 0.031345908, 0.020357063, 0.036818486, 0.057941414, 0.02202915, 0.05456248, -0.0010788095, 0.0062807095, 0.035390455, 0.0007585842, -0.034568362, 0.0029528835, 0.025872655, 0.026844813, -0.0076650498, -0.0072972584, -0.028605578, -0.012109216, 0.040585138, -0.04401547, -0.016611258, 0.047506593, 0.04040402, 0.036822572, 0.026940757, 0.007035624, 0.043494936, 0.031217743, 0.052097954, -0.013935086, -0.020070994, 0.00131935, -0.031350385, -0.033370994, -0.045080926, 0.046123326, 0.019063212, 0.035872955, 0.0044963025, -0.010484692, -0.019798664, -0.0052114013, 0.019801334, 0.031783275, -0.018794322, 0.032017037, 0.032530524, 0.016405638, -0.0388138, -0.026926344, -0.040274538, -0.021230241, -0.023918375, -0.0030149263, -0.033929706, 0.0075617186, -0.023613079, 0.07422112, 0.04437874, -0.036753092, -0.016630739, -0.06930593, -0.026506733, 0.005958725, -0.0089332005, -0.0129898265, -0.003507794, -0.016161723, 0.013940781, -0.0027737184, 0.044271104, -0.014426827, 0.010508009, 0.040800612, 0.031133305, -0.008688077, -0.015525487, -0.066046074, -0.024816912, -0.04244887, -0.012312995, -0.010183339, 0.025597721, 0.022375561, 0.014744547, -0.017313454, 0.0026319264, -0.030242732, 0.01014676, -0.041096717, -0.005326723, 0.039734017, 0.027196923, 0.020175908, 0.041571166, -0.04969955, 0.01361371, 0.016392408, 0.044326752, -0.016995655, -0.010014686, 0.008579357, 0.033027414, 0.04911093, 0.024309, 0.041040536, 0.046005107, -0.031947315, 0.0049236934, 0.022433966, -0.04614849, 0.036808968, 0.035015166, 0.033018187, -0.047600407, -0.02140971, 0.018138401, 0.0055952175, -0.020605622, 0.015138678, 0.024255453, -0.03483826, -0.06538493, -0.03926589, 0.0235159, -0.052137703, -0.052894503, -0.011985147, 0.015217182, 0.05346501, -0.04589632, -0.04868374, -0.015927853, -0.023936804, 0.042684525, -0.005856259, 0.007971605, 0.040346704, 0.026584305, 0.023574961, -0.0085781915, 0.033137705, 0.025171632, 0.03491466, 0.034005713, 0.02255272, 0.024131067, 0.016074855, -0.012018992, -0.012712488, 0.020301387, -0.02410342, -0.013383901, -0.015907636, 0.028849036, 0.027791593, -0.046718363, -0.007885546, 0.019444168, -0.031594507, -0.005617707, -0.0046808426, 0.030410783, -0.02085394, 0.041274644, -0.0048945807, 0.030088611, 0.042205166, -0.03087182, -0.016386399, 0.016776694, 0.0138749415, 0.038353756, 0.0070896163, -0.024911836, -0.01665645, 0.035824694, 0.039529614, -0.033193402, 0.065883495, 0.012891872, 0.017178878, -0.019834856, -0.024839813, -0.01123304, -0.06317404, -0.021355072, -0.033996414, -0.06726327, -0.0111284545, -0.04430501, 0.056159906, -0.07336556, -0.02678318, -0.009643973, 0.011455953, -0.022110563, 0.012122324, 0.03460247, -0.04165514, 0.029016158, 0.013044756, -0.014884067, -0.038643718, 0.0060539115, -0.0057379506, 0.009479012, -0.030450642, 0.066878065, 0.020571979, 0.03434267, 0.046375, -0.017981648, -0.11297966, -0.007879262, 0.044279702, -0.0060493518, -0.046985887, 0.031313952, 0.05215818, -0.040877227, -0.04959326, -0.008603043, 0.02457854, -0.063314855, 0.010619623, 0.025574611, 0.051122997, 0.008001694, -0.048742402, -0.03428849, -0.013046853, -0.040047348, 0.006056491, -0.030899905, 0.025837027, -0.057981584, -0.022408916, 0.0030647619, 0.006446675, 0.031231223, -0.01331776, -0.004892017, -0.0189681, 0.024663813, -0.038063355, 0.043250345, -0.038556542, -0.024693023, 0.045170296, -0.019576231, -0.012967551, -0.018645296, 0.021655109, 0.037303187, -0.0042916397, 0.022425592, -0.017797533, -0.028394347, -0.045502353, 0.015303989, -0.06540779, 0.010590826, -0.020084854, -0.0028066745, 0.0119754765, 0.0020542573, -0.014895159, 0.024245683, -0.004959684, -0.019711958, 0.04168154, 0.03133472, -0.016411992, -0.0081283925, -0.011762747, 0.040869612, 0.0026273925, 0.019898867, -0.040448975, -0.0034821262, -0.00501821, -0.007644585, -0.0070572835, -0.0296004, -0.02909171, 0.038702656, 0.039815813, -0.023736015, -0.013466968, -0.01653512, 0.0039299442, -0.07695936, -0.0026704099, 0.024979766, -0.041945927, -0.043168765, -0.020972168, -0.01517909, -0.05205682, -0.015819492, -0.04852126, 0.15720168, 0.026059797, 0.040793385, -0.026979702, -0.012102116, 0.033233996, 0.008692791, 0.02849639, 0.038179513, 0.009528373, -0.019348083, 0.018256765, 0.03286005, -0.07079013, 0.00735743, 0.05999147, 0.005536008, 0.03272625, 0.031364843, 0.0039787972, 0.03555288, -0.034430366, -0.0013481712, -0.0016830056, -0.028620033, -0.045411997, -0.019577498, 0.007832909, -0.037330475, 0.02427802, -0.039229833, -0.0037971651, -0.01996573, -0.017276457, 0.02489693, 0.015097212, 0.035939027, -0.029592209, 0.022125233, 0.024286069, -0.006720884, 0.0011854108, 0.0036076226, 0.03973079, -0.021429298, 0.05563558, 0.052824352, -0.000704112, -0.025388729, 0.005508252, 0.040989403, -0.0023094919, -0.019318692, -0.034174774, -0.0020948346, -0.0044218376, -0.030395538, -0.02575458, -0.0038592375, 0.037178047, 0.011411236, 0.038513515, -0.05675597, -0.021935647, 0.024190625, 0.0058852094, 0.0020067678, -0.029413123, -0.022348149, -0.0030042408, -0.06728152, -0.033250354, -0.019812748, 0.004247305, 0.009399409, -0.029773023, -0.028133288, 0.06261938, -0.0030583825, -0.0014320499, 0.02537287, -0.010761319, -0.035085835, 0.017681615, 0.040934727, -0.024228558, 0.057513904, 0.025384283, -0.03589352, -0.0011799774, 0.03560118, 0.017738841, -0.022415766, 0.047862783, 0.021147294, -0.08463089, 0.024595546, -0.013287359, -0.033646576, -0.0009804422, -0.022917379, 0.0027259982, -0.0439305, -0.0302873, -0.009381293, -0.02121824, 0.011970785, 0.035347957, 0.03563238, -0.026789129, 0.035881657, 0.0040325494, 0.022562318, -0.0072451863, 0.03146147, 0.027049176, 0.06281384, -0.037704714, 0.02278842, 0.02200708, -0.026770495, 0.06700601, -0.04987943, 0.08058686, -0.021111358, 0.051709067, 0.0012002586, -0.0209947, 0.028408874, 0.0024337475, 0.030251702, -0.015162337, -0.038669057, 0.017179362, 0.03291048, -0.0026581958, 0.064955436, -0.017213384, -0.042812344, 0.041025754, -0.024170134, 0.046137143, -0.017203914, 0.029693201, 0.022680005, 0.028730376, -0.013127024, -0.07368597, -0.033066493, 0.005253018, 0.06456792, 0.0004806567, 0.005131272, 0.0058063893, -0.027153367, -0.045406085, 0.016950954, 0.016593883, 0.054052576, -0.022582779, -0.044404037, 0.00705603, 0.012589965, 0.097894594, 0.030358236, 0.043028172, -0.022188444, 0.009755518, 0.0691229, 0.022298774, -0.021417832, -0.046682887, 0.0005498424, 0.024826586, 0.014994974, -0.03470143, -0.039935343, 0.03081718, -0.024319928, 0.020164747, -0.014237103, 0.022414578, 0.03507925, -0.013064879, -0.028728524, -0.0069431663, -0.0065439316, -0.029782653, -0.045835245, -0.021080822, -0.039900918, 0.098890066, -0.01845546, 0.0042844936, -0.046421036, 0.034154654, 0.033500012, 0.021324417, -0.053013664, -0.020348107, 0.004028104, -0.07150233, -0.025902433, -0.017128678, -0.047972668, -0.018578494, 0.0031385252, 0.021284686, 0.021532252, 0.031201182, 0.007794155, -0.017671319, -0.0034223164, 0.010837902, 0.025374277, 0.020951116, -0.016101502, 0.016335048, -0.022650395, 0.007496601, 0.021131288, 0.0116919335, 0.024902029, -0.011596728, -0.040976614, 0.0065638684, 0.0006247592, 0.03705029, -0.010927289, -0.0002448765, -0.0017740824, -0.006132811, -0.0075903498, -0.063066565, -0.028369894, -0.010993365, 0.028228085, 0.030171316, 0.029801195, -0.035337396, 0.021281762, -0.024532307, 0.046662953, -0.011108673, -0.004229011, 0.023159567, -0.04784731, -0.011086426, 0.034194864, -0.0055344915, -0.0032111802, -0.035264116, 0.033687208, 0.05387559, -0.012116111, -0.024197934, -0.002523972, -0.033238962, -0.032734457, -0.04435072, 0.004120296, 0.023445494, -0.021927789, 0.038763765, -0.012521632, 0.0046714293, 0.048754297, -0.051052168, 0.0030818912, -0.04307708, 0.048010867, -0.023517149, -0.014444148, -0.060646307, 0.082960345, 0.016580198, -0.038033288, -0.014875569, -0.010381301, -0.036331683, -0.0272889, 0.038158864, 0.0054460545, -0.00412238, 0.029797535, 0.04122033, -0.024880392, 0.033848803, 0.01944787, -0.023811549, -0.05070128, 0.029883126, -0.03667812, -0.007973736, -0.057661835, -0.035240773, -0.03874535, -0.025004948, -0.013481827, -0.042252775, 0.029997675, -0.041854978, -0.06579866, -0.014803064, -0.011150876, 0.016536793, -0.018866941, 0.011235533, 0.034709573, 0.03212958, -0.00906712, -0.048367713, 0.03693066, 0.02113606, 0.027995905, -0.0066593788, -0.0034246582, 0.005532681, -0.010661882, 0.051745024, -0.04969505, -0.030292625, -0.0014198018, -0.02563113, -0.00074315263, -0.007781813, 0.029980743, 0.016216611, 0.0079104025, -0.024725035, 0.00089510484, 0.014685914, -0.04309841, -0.024314225, -0.04356188, -0.055104844, -0.01343396, -0.01694522, -0.021111645, -0.04492946, -0.029171668, 0.0062913406, 0.026985696, -0.038751576, 0.031563982, 0.0061654835, -0.022360284, 0.010128895, -0.005108491, -0.0119582685, -0.016261956, 0.056016333, -0.002163816, -0.011593353, -0.05461722, 0.045469362, -0.04664052, -0.013775429, 0.021351242, -0.025422338, -0.030589527, -0.022667337, 0.011276052, -0.013522922, -0.019220226, 0.009910821, -0.0076468536, 0.033573702, -0.014687893, 0.01828357, 0.011090618, 0.054301612, -0.033874225, -0.0036304253, -0.026849715, 0.04737118, -0.03739468, -0.0031798498, 0.034271862, 0.013922721, -0.006200776, -0.0470712, -0.014216908, -0.01284839, 0.034971148, -0.013829705, -0.01265388, 0.03423995, 0.010420363, 0.013267174, -0.0055216034, 0.056103945, -0.019516885, 0.005123347, -0.07316491, -0.0066538276, 0.0072007477, 0.0038301377, -0.03003833, -0.013844631, -0.015737811, 0.0028639897, 0.01036993, -0.009252177, 0.015237155, 0.02361249, 0.02052098, -0.0009237124, -0.022420065, 0.03219099, 0.067991376, -0.005413276, 0.016430609, 0.019860886, 0.028569896, -0.049796406, 0.014890157, 0.030950041, 0.0020794247, 0.0062297964, 0.010497886, 0.024824321, -0.014437392, -0.0566433, 0.021550462, -0.029383823, -0.0050853128, 0.015755631, -0.01849466, 0.037325542, -0.025298795, -0.014102339, -0.012008115, 0.016013425, -0.04443121, 0.030534877, -0.028145416, -0.007714959, -0.0012772155, 0.042921532, -0.02271509, -0.018127091, 0.024551125, -0.045409366, -0.037986584, -0.015127914, 0.03530996, 0.044917703, 0.02071616, 0.006363538, 0.045369443, -0.008665244, 0.014031403, 0.027537718, 0.01756002, -0.038870342, -0.049487006, -0.0042024706, -0.029726768, -0.016281825, -0.062446702, -0.0086746905, -0.02393373, 0.050381918, -0.0003261012, -0.017756663, 0.042186625, 0.019775335, 0.043011863, 0.005269501, -0.023876607, -0.0073168008, -0.00089786656, -0.020522261, -0.021229248, -0.037683137, 0.029625071, 0.011948651, -0.042312197, 0.036162127, -0.013437291, -0.04204707, -0.025996255, 0.014462774, -0.04044129, 0.0078102294, 0.03572433, -0.042791646, -0.023418052, -0.039973926, -0.050879955, -0.03912128, -0.008004447, 0.029511819, -0.015222831, 0.004105793, -0.003046951, -0.0018042895, 0.020447595, 0.035100617, 0.033141848, -0.002001736, 0.057903487, -0.026949413, -0.04485731, -0.021472033, -0.032592744, 0.0069453926, -0.06019596, 0.008685544, -0.0005320232, 0.005925047, -0.012621645, 0.016243659, 0.008115558, -0.08346713, 0.061338544, -0.006730717, 0.044343453, 0.003226547, 0.015931347, -0.043674655, 0.025762353, -0.032944266, 0.016177291, -0.07765386, 0.020115234, 0.00016216836, -0.03127589, -0.005649965, -0.023834143, 0.04926012, -0.026157657, 0.025585478, -0.013913765, -0.031525344, -0.022008443, -0.016157242, -0.035934146, 0.018316992, -0.042544425, -0.018238315, 0.0018504179, -0.013600141, 0.023104759, -0.016253805, -0.02499635, 0.0378496, 0.02635304, 0.013511117, -0.00920587, -0.0037228242, 0.014942534, 0.011123744, -0.003521313, 0.010362956, -0.043435253, 0.029687144, -0.0062249415, -0.011777318, -0.0024399194, 0.017387053, -0.05342454, -0.011889302, 0.007417106, 0.024879051, -0.053923935, 0.040653095, 0.013428124, -0.013722141, 0.06854362, 0.021502519, 0.052568242, 0.051205948, 0.013071505, 0.022005804, -0.016511327, 0.023868915, 0.024556251, 0.04615034, 0.05070661, -0.004060078, -0.02002962, 0.017051686, -0.039919112, -0.0019798153, -0.010709447, 0.04901122, 0.055944346, -0.04242053, -0.021315528, 0.040812165, -0.03264552, -0.0022894032, 0.02457346, 0.0017750197, 0.026786918, -0.030886065, -0.024239482, -0.030370394, -0.040238287, -0.00630131, -0.012920513, 0.02949447, 0.06354811, -0.0077935588, -0.0069032563, -0.002468092, 0.010400846, 0.010169008, 0.03351035, -0.014592436, 0.0044351225, 0.030535512, 0.015723651, 0.03573328, -0.010834245, 0.023036718, -0.03358507, 0.016948659, -0.039716847, 0.03608021, -0.024967987, -0.010776639, -0.0010107715, 0.008065328, -0.008218733, -0.007881336, -0.021835906, -0.016634611, 0.03677422, 0.0066643334, 0.016943587, 0.022064205, 0.008388702, -0.009166648, -0.018789105, 0.0147469]

In [8]:
len(embedding_result)

1024

In [9]:
data = ['저는 배가 고파요',
        '저기 배가 지나가네요',
        '굶어서 허기가 지네요',
        '허기 워기라는 게임이 있는데 즐거워',
        '스팀에서 재밌는 거 해야지',
        '스팀에어프라이어로 연어구이 해먹을거야']

In [10]:
pd.DataFrame(data, columns=['text'])

                   text
0             저는 배가 고파요
1           저기 배가 지나가네요
2           굶어서 허기가 지네요
3   허기 워기라는 게임이 있는데 즐거워
4        스팀에서 재밌는 거 해야지
5  스팀에어프라이어로 연어구이 해먹을거야

In [11]:
df = pd.DataFrame(data, columns=['text'])
df.head()

                  text
0            저는 배가 고파요
1          저기 배가 지나가네요
2          굶어서 허기가 지네요
3  허기 워기라는 게임이 있는데 즐거워
4       스팀에서 재밌는 거 해야지

In [12]:
df.apply(lambda row: get_embedding(row.text), axis=1)

0    [0.04318022, -0.009389596, -0.029974656, -0.02...
1    [0.027747892, 3.1770283e-05, -0.032191023, -0....
2    [0.03211817, -0.003851689, -0.018075485, -0.03...
3    [0.024652768, -0.008114235, -0.034386653, -0.0...
4    [0.0151690245, -0.0038775196, -0.021856694, -0...
5    [0.025275795, 0.001905821, -0.0082368795, -0.0...
dtype: object

In [13]:
df['embedding'] = df.apply(lambda row: get_embedding(row.text), axis=1)
df.head()

                  text                                          embedding
0            저는 배가 고파요  [0.04318022, -0.009389596, -0.029974656, -0.02...
1          저기 배가 지나가네요  [0.027747892, 3.1770283e-05, -0.032191023, -0....
2          굶어서 허기가 지네요  [0.03211817, -0.003851689, -0.018075485, -0.03...
3  허기 워기라는 게임이 있는데 즐거워  [0.024652768, -0.008114235, -0.034386653, -0.0...
4       스팀에서 재밌는 거 해야지  [0.0151690245, -0.0038775196, -0.021856694, -0...

In [14]:
# 코사인 유사도 (벡터의 유사도 구하는 방법)

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

In [15]:
def return_answer_candidate(df, query):
     query_embedding = get_embedding(query)
     df['similarity'] = df.embedding.apply(lambda x: cos_sim(np.array(x), np.array(query_embedding)))
     results_co = df.sort_values(by=['similarity'], ascending=False, ignore_index=True)  # 내림차순
     return results_co

In [16]:
sim_result = return_answer_candidate(df, '김밥 한 줄 먹었더니 강제 다이어트야')
sim_result

,text,embedding,similarity
0,굶어서 허기가 지네요,"[0.03211817, -0.003851689, -0.018075485, -0.03...",0.859199
1,저는 배가 고파요,"[0.04318022, -0.009389596, -0.029974656, -0.02...",0.853677
2,스팀에어프라이어로 연어구이 해먹을거야,"[0.025275795, 0.001905821, -0.0082368795, -0.0...",0.834415
3,허기 워기라는 게임이 있는데 즐거워,"[0.024652768, -0.008114235, -0.034386653, -0.0...",0.828588
4,저기 배가 지나가네요,"[0.027747892, 3.1770283e-05, -0.032191023, -0....",0.806568
5,스팀에서 재밌는 거 해야지,"[0.0151690245, -0.0038775196, -0.021856694, -0...",0.804424

In [17]:
df.to_csv('df_cos_sim.csv', index=False, encoding='utf-8')

In [18]:
pd.read_csv('df_cos_sim.csv')

,text,embedding,similarity
0,저는 배가 고파요,"[0.04318022, -0.009389596, -0.029974656, -0.02...",0.853677
1,저기 배가 지나가네요,"[0.027747892, 3.1770283e-05, -0.032191023, -0....",0.806568
2,굶어서 허기가 지네요,"[0.03211817, -0.003851689, -0.018075485, -0.03...",0.859199
3,허기 워기라는 게임이 있는데 즐거워,"[0.024652768, -0.008114235, -0.034386653, -0.0...",0.828588
4,스팀에서 재밌는 거 해야지,"[0.0151690245, -0.0038775196, -0.021856694, -0...",0.804423
5,스팀에어프라이어로 연어구이 해먹을거야,"[0.025275795, 0.001905821, -0.0082368795, -0.0...",0.834415