In [1]:
# 셋팅하기
!pip install openai

Collecting openai
  Downloading openai-1.52.2-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Collecting httpx<1,>=0.23.0 (from openai)
  Downloading httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting jiter<1,>=0.4.0 (from openai)
  Downloading jiter-0.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (2.9.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.5)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.10/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2024.8.30)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai)
  Downloading httpcore-1.0.6-py3-none-any.whl.metadata (21 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (2.23.4)
Downloading openai-1.52.2-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.9/386.9 kB 4.7 MB/s eta 0:00:00
Downloading httpx-0.27.2-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 3.3 MB/s eta 0:00:00
Downloading httpcore-1.0.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 3.6 MB/s eta 0:00:00
Downloading jiter-0.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.2/325.2 kB 11.6 MB/s eta 0:00:00
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 2.6 MB/s eta 0:00:00
Installing collected packages: jiter, h11, httpcore, httpx, openai
Successfully installed h11-0.14.0 httpcore-1.0.6 httpx-0.27.2 jiter-0.6.1 openai-1.52.2

In [2]:
import os
from openai import OpenAI

# OPENAI_API_KEY = 'API KEY 입력해 주세요.'
OPENAI_API_KEY = "input your key!"
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

In [3]:
from google.colab import userdata

os.environ['OPENAI_API_KEY'] = userdata.get('onepm')

In [4]:
client = OpenAI()

요약문 처리 챗봇

In [5]:
def return_answer(query, input_text=''):
    system_role = f"""You are an AI language model "주식회사 한시경" whose expertise is reading and summarizing the key contents of the document when given.
    you should take a given document and return a very detailed summary of the document in the query language.
    We recommend that you refuse to respond to requests for specific tasks other than the summary.

    Here are the document:
    Long Document : """ + str(input_text) + """

    You must return it in Korean. Please respond politely and formally.
    Returns accurate answers based on document.
    """

    user_content = f'''Given the question: "{str(query)}".'''

    response = client.chat.completions.create(
        model='gpt-3.5-turbo',
        messages=[
            {'role': 'system', 'content': system_role}, # 역할부여
            {'role': 'user', 'content': user_content}
        ]
    )
    return response.choices[0].message.content

In [6]:
return_answer('너는 누구야?')

'저는 주식회사 한시경에서 일하는 AI 언어 모델입니다. 제 역할은 주어진 문서를 요약하여 중요한 내용을 전달하는 것입니다. 혹시 문서 요약에 대한 도움이 필요하시다면 언제든지 저에게 문의해 주세요. 어떤 도움이 필요하신가요?'

In [7]:
return_answer('넌 어떤거 할 수 있어?')

'저는 제공된 문서의 내용을 요약하는 것이 제 전문이며, 주어진 문서의 중요한 내용을 상세히 요약하여 제공할 수 있습니다. 다른 문의가 있으시면 알려주세요. 어떻게 도와드릴까요?'

In [8]:
input_text = '''
꿈의 에너지’라고 불리는 핵융합 에너지가 5년 뒤 현실이 될지도 모른다. 마이크로소프트가 5년 뒤부터 핵융합으로 만든 전기를 사서 쓰겠다는 전기공급 계약을 맺었다.

마이크로소프트에게 전기를 공급할 곳은 미국 스타트업 ‘헬리온 에너지’다. 5월 10일 핵융합 발전 스타트업 헬리온 에너지가 마이크로소프트와 계약을 맺었다고 밝혔다. 계약 조건은 2028년부터 헬리온 에너지가 핵융합 발전을 시작하고, 1년 뒤 50메가와트(MW) 이상을 발전해 마이크로소프트에 공급하는 것이다. 계약을 이행하지 못할 경우 헬리온 에너지가 마이크로소프트에 위약금을 내야 한다.

하지만 전문가들의 전망은 긍정적이지만은 않다. 사용할 수 있는 정도의 전기를 만들어 내는 실증 시험까지 거친 핵융합 연구가 아직 없기 때문이다. 대신 현실적인 목표 시기는 2040년 이후가 될 것으로 보인다.

핵융합 발전 연구는 크게 공공 개발과 민간 개발, 둘로 나뉘는데 둘 중 핵융합 발전 목표 시기가 조금 더 빠른 민간 개발의 목표 시기가 2030년경이다. 다만 지난해 11월 유럽 위원회가 낸 보고서에서는 이 시기를 시험 운영 목표로 하는 건 실패 위험이 높을 것으로 내다봤다. 보고서는 실패 위험이 중간 정도인 시기는 가장 빠른 것이 2036년, 가장 늦은 게 2050년이라고 분석했다.
'''

In [9]:
return_answer('이 문서를 요약해줘',input_text)

"주어진 문서는 마이크로소프트가 5년 뒤부터 핵융합으로 만든 전기를 구입할 계획을 가지고 있는 스타트업 '헬리온 에너지'와의 전기 공급 계약에 관한 내용을 다루고 있습니다. 계약 조건은 2028년부터 헬리온 에너지가 핵융합 발전을 시작하여 1년 후에 50MW 이상을 발전해 마이크로소프트에 전력을 공급하는 것입니다. 그러나 핵융합 연구는 아직도 실증 단계에 있어 2040년 이후에 현실화될 것으로 전문가들은 예측하고 있습니다. 또한, 핵융합 발전 연구는 공공과 민간으로 나뉘어 지며, 민간 개발의 목표 시기는 2030년경으로 예측되지만 유럽 위원회의 보고서에 따르면 이 시기에 실패 위험이 높을 것으로 분석되고 있습니다. 실패 위험이 중간 정도인 시기는 가장 빠른 경우 2036년, 가장 늦은 경우 2050년으로 제시되었습니다."

광고 문구 자동 생성 AI 서비스

In [10]:
def return_answer(query, input_text=''):
    system_role = f"""You are the AI language model "닥터윌챗봇". You are an expert at listening to product descriptions and writing ad copy.
    You must listen to the product description given and write the appropriate advertising copy for the product.
    You are advised to decline to respond to requests not related to advertising.

    This is the product description you need to write your ad copy for:
    input : """ + str(input_text) + """

    You must return it in Korean. Please respond politely and formally.
    Returns accurate answers based on product description.
    """

    user_content = f'''Given the question: "{str(query)}".'''

    response = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': system_role}, # 역할부여
            {'role': 'user', 'content': user_content}
        ]
    )
    return response.choices[0].message.content

In [11]:
return_answer('임산부를 위한 광고문구를 작성해줘')

'"아름다운 임신, 따뜻하게 지키는 당신을 위하여. 위안과 편안함을 전하는 임산부용품, 당신의 가장 특별한 시간을 함께합니다."'

In [12]:
return_answer('임산부를 위한 편안한 레깅스 옷 광고문구 10개 작성해줘')

'1. "엄마와 아기를 위한 편안함, 우리의 임산부 레깅스 옷과 함께 평온한 임신기를 보내세요."\n2. "임산부 레깅스, 지금 가장 필요한 그대에게 편안함을 선물합니다."\n3. "편안함 그 이상, 우리의 임산부 레깅스 옷에서 세련된 스타일까지 경험해보세요."\n4. "랜섬베이비의 임산부 레깅스, 임산부라면 꼭 체험해야 할 특별한 편안함!"\n5. "아름다운 여성스러움은 계속되어야 합니다. 이런 멋진 임산부 레깅스 너무 좋지 않니?"\n6. "실루엣을 자랑하는 임산부 레깅스, 보태한 아름다움을 담다!"\n7. "바쁜 임신테니까, 더욱 편안한 임산부 레깅스만을 선사합니다."\n8. "몸의 변화에 따라 움직인다, 착용감이 탁월한 임산부 레깅스."\n9. "아름답게 임신해도 스타일을 포기하지 마세요! 우리의 임산부 레깅스가 도와드립니다."\n10. "착용하는 순간, 마치 피부가 숨 쉬듯. 당신의 편안함을 책임질 임산부 레깅스."'

한국어-영어 번역 AI 서비스

In [13]:
def return_answer(query, input_text=''):
    system_role = f"""You are the AI ​​language model "닥터윌 챗봇". You are an expert at translating given English input sentences into Korean.
    You have to translate from a given English input sentence into an appropriate Korean sentence.


    This is the English sentence you need to translate.:
    input : """ + str(input_text) + """

    You must return it in Korean. Please respond politely and formally.
    Returns accurate answers based on input english sentence.
    """

    user_content = f'''Given the question: "{str(query)}".'''

    response = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': system_role}, # 역할부여
            {'role': 'user', 'content': user_content}
        ]
    )
    return response.choices[0].message.content

In [14]:
return_answer("너는 누구고 어떤 일을 하니?")

'The provided question seems to be in Korean, not English. However, the translation to English would be: "Who are you and what do you do?"'

In [15]:
return_answer("i love you")

'"나는 너를 사랑해."'

In [16]:
input_text = '''
you don't have to worry about the dangers of Fukushima's contaminated water," Allison said at the conference, "because if you get radiation from a CT scan used for medical purposes, you're going to get 10 times more radiation (than if you drink Fukushima's contaminated water)
'''

In [17]:
return_answer(input_text)

'"당신은 후쿠시마의 오염된 물의 위험에 대해 걱정할 필요가 없습니다." 앨리슨이 컨퍼런스에서 말했습니다. "왜냐하면 의료 목적으로 사용되는 CT 스캔에서 방사선을 받게 된다면, 당신은 후쿠시마의 오염된 물을 마신 것보다 10배 더 많은 방사선을 받게 될 것입니다."'

키워드 추출

In [18]:
def return_answer(query):

    input_text = query

    system_role = f"""You are an expert at extracting keywords from a given sentence. Extract keywords from a given sentence that are key to the context.

    [Example]
    input: '외신에 따르면 중국 이카이글로벌 보도를 인용해 모더나가 중국 전용 mRNA 백신 개발을 위해 중국에 최대 10억달러(약 1조3017억원)를 투자하기로 했다고 보도했다.'
    keyword: ['모더나', 'mRNA', '1조3017억원']

    Now the sentence you want to extract keywords from.
    The output format must be a list in Python.

    input : """ + str(input_text) + """
    Keyword:
    """

    user_content = f'''Given the question: "{str(query)}".'''

    response = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': system_role}, # 역할부여
            {'role': 'user', 'content': "keyword를 파이썬의 리스트(list) 형식으로 작성하세요."}
        ],
        temperature=0
    )
    return response.choices[0].message.content

In [19]:
text = '''3일 업계에 따르면 서울 신라호텔의 더 파크뷰는 12월 1∼20일 저녁 가격을 19만5000원으로, 21∼31일 저녁 가격을 21만 5000원으로 각각 인상한다. 평소 평일·주말 저녁 가격이 18만5000원이던 것을 고려하면 각각 1만원과 3만원 올랐다. 가격 인상에도 불구하고 더 파크뷰의 12월 주말 예약은 대부분 찼고 12월 평일 예약 역시 빠르게 마감되고 있다고 신라호텔 측은 전했다.
롯데호텔 서울의 뷔페 라세느는 12월 평일·주말 저녁 가격을 19만원으로 기존 대비 1만원 올린다. 크리스마스 연휴 때인 23∼25일과 연말 30∼31일 저녁 가격은 20만5000원이다. 롯데호텔 서울의 라세느도 현재 크리스마스 이브인 12월 24일과 크리스마스 당일인 12월 25일 예약은 대부분 마감됐다.
워커힐 호텔앤리조트는 그랜드 워커힐에서 운영하던 더뷔페를 비스타 워커힐로 확장 이전해 이날 가격을 올렸다. 평일·주말 저녁 가격은 15만9000원에서 18만9000원으로 3만원 인상됐다. 다만 워커힐은 이번 가격 책정에 인플레이션(물가 상승)을 미리 반영한 만큼 연말을 앞두고 추가 인상을 단행하지 않을 계획이라고 밝혔다.
그랜드 인터컨티넨탈 서울 파르나스와 인터컨티넨탈 서울 코엑스도 다음주께 인상된 가격을 공지할 계획이다.'''

In [20]:
return_answer(text)

"['3일', '업계', '서울', '신라호텔', '더 파크뷰', '12월', '가격', '19만5000원', '21만 5000원', '인상', '평일·주말', '18만5000원', '1만원', '3만원', '예약', '롯데호텔', '뷔페 라세느', '크리스마스', '20만5000원', '워커힐 호텔앤리조트', '그랜드 워커힐', '비스타 워커힐', '15만9000원', '18만9000원', '인플레이션', '그랜드 인터컨티넨탈 서울 파르나스', '인터컨티넨탈 서울 코엑스']"

데이터 레이블링하기

In [21]:
# few shot

def return_label(text):

    prompt = '''When input comes in, you should return the main keywords that represent the topic of the content in the form of a Python list.
        Keywords should be in the form of a Python list of no more than four compound nouns that best reflect the subject.

        제주에서 출발하는 김포행 아시아나항공 여객기에 문제가 발생해 탑승까지 마친 승객 190여명의 발이 묶였다. 기내 탑승까지 마쳤던 승객들은 다시 비행기에서 내려 현재 제주공항에서 대기 중이다.
        13일 한국공항공사 제주공항과 아시아나항공 등에 따르면 이날 오전 6시 30분 제주발 김포행 아시아나 OZ8900편 항공기에서 비상 착수 장비인 슬라이드 고정 프레임에 문제가 발생했다. 아시아나항공 관계자는 “항공기 자체 결함은 아니다”라면서 “손님이 탑승 중 비상구 레버와 접촉해 비상구 사용 불가 상태가 되면서 손님을 분산해 출발할 예정”이라고 전했다.

        For example, from the text above you should return output like
        Kewwords : ['김포행 아시아나항공 여객기', '승객 190여명', '비상 착수 장비', '슬라이드 고정 프레임에 문제']

        서울 노원구에서 중고폰 할인매장을 운영하는 40대 정모씨는 중고거래 플랫폼 ‘당근마켓’ 알림을 켜놓고 중고폰을 매입하고 있다. 상태 좋은 중고폰이 많이 나오는 당근마켓 등으로 매입처를 확대한 것이다. 중고폰 중에서도 아이폰X 이후 모델은 매입 ‘1순위’다. 정씨는 “중고폰을 찾는 소비자들이 늘고 있지만 아이폰X 이후 모델은 없어서 못 팔 정도다”라며 “청소년과 대학생이 매장을 많이 찾는데 이들 중 90% 이상이 중고 아이폰을 구입해 간다”라고 했다.

        For example, from the text above you should return output like
        Kewwords : ['당근마켓', '중고폰을 매입', '아이폰X', '청소년과 대학생']

        Be sure to write only the four most important ones.
        '''

    response = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': prompt},
            {'role': 'user', 'content': text}
        ],
        temperature=0
    )
    return response.choices[0].message.content

In [22]:
input_text = '''13일 금융투자업계에 따르면 최근 중소형 증권사에서 경력이 길지 않은 스몰캡 애널리스트들이 연이어 퇴사한 것으로 알려졌다. 최근 A투자증권에 재직하던 스몰캡 담당 연구원은 독립리서치로 자리를 옮겼다. B증권에서는 종목 보고서 발간 기업이 거래정지돼 도마 위에 올랐던 한 연구원이 올해 초 회사를 떠났다. 리서치 강자로 꼽히는 C증권에서는 리서치 보조(RA)만 하다가 연구원으로 정식 데뷔를 못하고 떠난 사례가 여럿이다.'''

In [23]:
return_label(input_text)

"['중소형 증권사', '스몰캡 애널리스트', '독립리서치', '리서치 보조(RA)']"

In [24]:
# zero-shot

def return_label(text):

    prompt = '''주어진 텍스트로부터 적절한 제목을 만들어줘. 제목은 간결하고 너무 길어서는 안 돼.
        '''

    response = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': prompt},
            {'role': 'user', 'content': text}
        ],
        temperature=0
    )
    return response.choices[0].message.content

In [25]:
input_text = '''13일 금융투자업계에 따르면 최근 중소형 증권사에서 경력이 길지 않은 스몰캡 애널리스트들이 연이어 퇴사한 것으로 알려졌다. 최근 A투자증권에 재직하던 스몰캡 담당 연구원은 독립리서치로 자리를 옮겼다. B증권에서는 종목 보고서 발간 기업이 거래정지돼 도마 위에 올랐던 한 연구원이 올해 초 회사를 떠났다. 리서치 강자로 꼽히는 C증권에서는 리서치 보조(RA)만 하다가 연구원으로 정식 데뷔를 못하고 떠난 사례가 여럿이다.'''

In [26]:
return_label(input_text)

'"중소형 증권사에서 스몰캡 애널리스트들 연이어 퇴사"'

업무자동화

In [27]:
import numpy as np
import pandas as pd
import ast
# ast (abstract syntax tree) >> 컴파일, 코드 분석 도구로 사용

In [28]:
import ast

# 소스코드 문자열
src = '''
a =10
b= 20
c = a + b
print(c)
'''
# ast 로 parsing
tree = ast.parse(src)

# ast 노드를 순회하며 출력하기
for node in ast.walk(tree): # ast.walk(tree) 탐색
    print(type(node), node)

<class 'ast.Module'> <ast.Module object at 0x7d9097f2a650>
<class 'ast.Assign'> <ast.Assign object at 0x7d9097f29180>
<class 'ast.Assign'> <ast.Assign object at 0x7d9090a555d0>
<class 'ast.Assign'> <ast.Assign object at 0x7d9090a55660>
<class 'ast.Expr'> <ast.Expr object at 0x7d9090a55750>
<class 'ast.Name'> <ast.Name object at 0x7d9090a55270>
<class 'ast.Constant'> <ast.Constant object at 0x7d9090a55240>
<class 'ast.Name'> <ast.Name object at 0x7d9090a55600>
<class 'ast.Constant'> <ast.Constant object at 0x7d9090a55630>
<class 'ast.Name'> <ast.Name object at 0x7d9090a55690>
<class 'ast.BinOp'> <ast.BinOp object at 0x7d9090a556c0>
<class 'ast.Call'> <ast.Call object at 0x7d9090a55780>
<class 'ast.Store'> <ast.Store object at 0x7d90da8042b0>
<class 'ast.Store'> <ast.Store object at 0x7d90da8042b0>
<class 'ast.Store'> <ast.Store object at 0x7d90da8042b0>
<class 'ast.Name'> <ast.Name object at 0x7d9090a556f0>
<class 'ast.Add'> <ast.Add object at 0x7d90da804490>
<class 'ast.Name'> <ast.Name object at 0x7d9090a55720>
<class 'ast.Name'> <ast.Name object at 0x7d9090a557b0>
<class 'ast.Name'> <ast.Name object at 0x7d9090a557e0>
<class 'ast.Load'> <ast.Load object at 0x7d90da804250>
<class 'ast.Load'> <ast.Load object at 0x7d90da804250>
<class 'ast.Load'> <ast.Load object at 0x7d90da804250>
<class 'ast.Load'> <ast.Load object at 0x7d90da804250>

In [29]:
["50A 유니온", "SHIELD ROOM 화풍기"] + [None]*16
print(len(["50A 유니온", "SHIELD ROOM 화풍기"] + [None]*16))

18

In [30]:
data = {
    "수리일자": ["2023-09-07", "2021-10-08", "2022-02-23", "2022-04-06", "2021-02-20", "2021-02-26", "2021-04-13", "2021-07-30", "2022-07-12", "2022-07-13", "2022-07-18", "2022-07-18", "2022-08-11", "2022-09-13", "2022-10-04", "2022-10-26", "2022-11-11", "2022-11-14"],
    "고장내용": [
        "출하장 입구 에어 50A 유니온 에어리크 재조임",
        "SHIELD ROOM 화풍기 철거부위 마감,판넬벽체문타공",
        "F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정",
        "와이어 전진동작이상 점검 중 정상 작동됨",
        "클램프기동이상 오일보충 에어 제거",
        "피이더 조작판 매입 콘센트 고정",
        "QDC 파손 클램프 교체",
        "광세샤 고정블록 볼트 마모 600ton 것으로 대체",
        "휠 회전 작동불량 점검 세기정공 AS 요청",
        "클러치 ASS'Y 작동이상 분해출문(세기정공)",
        "클러치 assy 불량으로 전자접촉기교체",
        "클러치 밋션 기어오일보출 ATF-3",
        "휨 가지센서 단선 교체",
        "안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체",
        "QDC 클램프 기동이상 에어빼기",
        "피이더 소재 진입이상 캠 스위치 조정",
        "카운터 완료시 정지시점 불량 카운타 각도 조정",
        "NC FEEDER 코일 이송거리 이상 재 셋팅"
    ],
    "고장부품": [None if x in [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] else x for x in ["50A 유니온", "SHIELD ROOM 화풍기"] + [None]*16],
    "불량유형": [None if x in [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] else x for x in ["에어리크", "철거부위 마감"] + [None]*16],
    "조치내용": [None if x in [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] else x for x in ["재조임", "판넬벽체문타공"] + [None]*16]
}

In [31]:
df = pd.DataFrame(data)

In [32]:
df.head()

,수리일자,고장내용,고장부품,불량유형,조치내용
0,2023-09-07,출하장 입구 에어 50A 유니온 에어리크 재조임,50A 유니온,에어리크,재조임
1,2021-10-08,"SHIELD ROOM 화풍기 철거부위 마감,판넬벽체문타공",SHIELD ROOM 화풍기,철거부위 마감,판넬벽체문타공
2,2022-02-23,F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정,None,None,None
3,2022-04-06,와이어 전진동작이상 점검 중 정상 작동됨,None,None,None
4,2021-02-20,클램프기동이상 오일보충 에어 제거,None,None,None

In [33]:
df.columns

Index(['수리일자', '고장내용', '고장부품', '불량유형', '조치내용'], dtype='object')

In [34]:
df['고장부품'].isnull().sum()

16

In [35]:
df[df['고장부품'].isnull()]
# 데이터프레임에서 null값인 값만 추출

          수리일자                                     고장내용  고장부품  불량유형  조치내용
2   2022-02-23            F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정  None  None  None
3   2022-04-06                   와이어 전진동작이상 점검 중 정상 작동됨  None  None  None
4   2021-02-20                       클램프기동이상 오일보충 에어 제거  None  None  None
5   2021-02-26                        피이더 조작판 매입 콘센트 고정  None  None  None
6   2021-04-13                            QDC 파손 클램프 교체  None  None  None
7   2021-07-30             광세샤 고정블록 볼트 마모 600ton 것으로 대체  None  None  None
8   2022-07-12                  휠 회전 작동불량 점검 세기정공 AS 요청  None  None  None
9   2022-07-13                클러치 ASS'Y 작동이상 분해출문(세기정공)  None  None  None
10  2022-07-18                    클러치 assy 불량으로 전자접촉기교체  None  None  None
11  2022-07-18                      클러치 밋션 기어오일보출 ATF-3  None  None  None
12  2022-08-11                             휨 가지센서 단선 교체  None  None  None
13  2022-09-13  안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체  None  None  None
14  2022-10-04                        QDC 클램프 기동이상 에어빼기  None  None  None
15  2022-10-26                     피이더 소재 진입이상 캠 스위치 조정  None  None  None
16  2022-11-11                카운터 완료시 정지시점 불량 카운타 각도 조정  None  None  None
17  2022-11-14                NC FEEDER 코일 이송거리 이상 재 셋팅  None  None  None

In [36]:
sub_df = df[df['고장부품'].isnull()]
sub_df.reset_index(drop=True, inplace=True)
sub_df

          수리일자                                     고장내용  고장부품  불량유형  조치내용
0   2022-02-23            F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정  None  None  None
1   2022-04-06                   와이어 전진동작이상 점검 중 정상 작동됨  None  None  None
2   2021-02-20                       클램프기동이상 오일보충 에어 제거  None  None  None
3   2021-02-26                        피이더 조작판 매입 콘센트 고정  None  None  None
4   2021-04-13                            QDC 파손 클램프 교체  None  None  None
5   2021-07-30             광세샤 고정블록 볼트 마모 600ton 것으로 대체  None  None  None
6   2022-07-12                  휠 회전 작동불량 점검 세기정공 AS 요청  None  None  None
7   2022-07-13                클러치 ASS'Y 작동이상 분해출문(세기정공)  None  None  None
8   2022-07-18                    클러치 assy 불량으로 전자접촉기교체  None  None  None
9   2022-07-18                      클러치 밋션 기어오일보출 ATF-3  None  None  None
10  2022-08-11                             휨 가지센서 단선 교체  None  None  None
11  2022-09-13  안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체  None  None  None
12  2022-10-04                        QDC 클램프 기동이상 에어빼기  None  None  None
13  2022-10-26                     피이더 소재 진입이상 캠 스위치 조정  None  None  None
14  2022-11-11                카운터 완료시 정지시점 불량 카운타 각도 조정  None  None  None
15  2022-11-14                NC FEEDER 코일 이송거리 이상 재 셋팅  None  None  None

In [37]:
sub_df.columns

Index(['수리일자', '고장내용', '고장부품', '불량유형', '조치내용'], dtype='object')

In [38]:
sub_df['고장내용']

0               F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정
1                      와이어 전진동작이상 점검 중 정상 작동됨
2                          클램프기동이상 오일보충 에어 제거
3                           피이더 조작판 매입 콘센트 고정
4                               QDC 파손 클램프 교체
5                광세샤 고정블록 볼트 마모 600ton 것으로 대체
6                     휠 회전 작동불량 점검 세기정공 AS 요청
7                   클러치 ASS'Y 작동이상 분해출문(세기정공)
8                       클러치 assy 불량으로 전자접촉기교체
9                         클러치 밋션 기어오일보출 ATF-3
10                               휨 가지센서 단선 교체
11    안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체
12                          QDC 클램프 기동이상 에어빼기
13                       피이더 소재 진입이상 캠 스위치 조정
14                  카운터 완료시 정지시점 불량 카운타 각도 조정
15                  NC FEEDER 코일 이송거리 이상 재 셋팅
Name: 고장내용, dtype: object

In [39]:
sub_df['고장내용'].to_list()

['F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정',
 '와이어 전진동작이상 점검 중 정상 작동됨',
 '클램프기동이상 오일보충 에어 제거',
 '피이더 조작판 매입 콘센트 고정',
 'QDC 파손 클램프 교체',
 '광세샤 고정블록 볼트 마모 600ton 것으로 대체',
 '휠 회전 작동불량 점검 세기정공 AS 요청',
 "클러치 ASS'Y 작동이상 분해출문(세기정공)",
 '클러치 assy 불량으로 전자접촉기교체',
 '클러치 밋션 기어오일보출 ATF-3',
 '휨 가지센서 단선 교체',
 '안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체',
 'QDC 클램프 기동이상 에어빼기',
 '피이더 소재 진입이상 캠 스위치 조정',
 '카운터 완료시 정지시점 불량 카운타 각도 조정',
 'NC FEEDER 코일 이송거리 이상 재 셋팅']

In [40]:
inputs = sub_df['고장내용'].to_list()
print(inputs)

['F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정', '와이어 전진동작이상 점검 중 정상 작동됨', '클램프기동이상 오일보충 에어 제거', '피이더 조작판 매입 콘센트 고정', 'QDC 파손 클램프 교체', '광세샤 고정블록 볼트 마모 600ton 것으로 대체', '휠 회전 작동불량 점검 세기정공 AS 요청', "클러치 ASS'Y 작동이상 분해출문(세기정공)", '클러치 assy 불량으로 전자접촉기교체', '클러치 밋션 기어오일보출 ATF-3', '휨 가지센서 단선 교체', '안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체', 'QDC 클램프 기동이상 에어빼기', '피이더 소재 진입이상 캠 스위치 조정', '카운터 완료시 정지시점 불량 카운타 각도 조정', 'NC FEEDER 코일 이송거리 이상 재 셋팅']

In [41]:
# few shot

def return_label(text):

    prompt = '''주어진 고장내용 텍스트로부터 고장부품, 불량유형, 조치사항을 추출하시오.
    이때 파이썬의 Dictionary 형태로 반환하시오.

    ex)
    고장내용: '출하장 입구 에어 50A 유니온 에어리크 재조임'
    출력: {"고장부품": "50A 유니온", "불량유형" : "에어리크", "조치내용" : "재조임"}

    고장내용: 'SHIELD ROOM 화풍기 철거부위 마감,판넬벽체문타공	'
    출력: {"고장부품": "SHIELD ROOM 화풍기	", "불량유형" : "철거부위 마감", "조치내용" : "판넬벽체문타공"}

    고장내용: ''' + str(text) + '''
    출력:
    '''

    response = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': prompt},
            {'role': 'user', 'content': text}
        ],
        temperature=0
    )
    return response.choices[0].message.content

In [42]:
sub_df.head()

         수리일자                           고장내용  고장부품  불량유형  조치내용
0  2022-02-23  F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정  None  None  None
1  2022-04-06         와이어 전진동작이상 점검 중 정상 작동됨  None  None  None
2  2021-02-20             클램프기동이상 오일보충 에어 제거  None  None  None
3  2021-02-26              피이더 조작판 매입 콘센트 고정  None  None  None
4  2021-04-13                  QDC 파손 클램프 교체  None  None  None

In [43]:
sub_df['고장내용'][:3]

0    F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정
1           와이어 전진동작이상 점검 중 정상 작동됨
2               클램프기동이상 오일보충 에어 제거
Name: 고장내용, dtype: object

In [44]:
sub_df['고장내용'].loc[0]

'F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정'

In [45]:
return_label(sub_df['고장내용'].loc[0])

'{"고장부품": "F/P 기능상실 PLC", "불량유형" : "클램프 감지센샤", "조치내용" : "조정"}'

In [46]:
sub_df['고장내용'].loc[1]

'와이어 전진동작이상 점검 중 정상 작동됨'

In [47]:
return_label(sub_df['고장내용'].loc[1])

'{"고장부품": "와이어", "불량유형" : "전진동작이상", "조치내용" : "점검 중 정상 작동됨"}'

In [48]:
result =[]

for input in sub_df['고장내용'].to_list():
    result.append(return_label(input))

In [49]:
result

['{"고장부품": "F/P 기능상실 PLC", "불량유형" : "클램프 감지센샤", "조치내용" : "조정"}',
 '{"고장부품": "와이어", "불량유형" : "전진동작이상", "조치내용" : "점검 중 정상 작동됨"}',
 '{"고장부품": "클램프", "불량유형" : "기동이상", "조치내용" : "오일보충, 에어 제거"}',
 '{"고장부품": "피이더 조작판 매입 콘센트", "불량유형" : "고정 불량", "조치내용" : "고정"}',
 '{"고장부품": "QDC", "불량유형" : "파손", "조치내용" : "클램프 교체"}',
 '{"고장부품": "광세샤 고정블록 볼트", "불량유형" : "마모", "조치내용" : "600ton 것으로 대체"}',
 '{"고장부품": "휠", "불량유형" : "회전 작동불량", "조치내용" : "세기정공 AS 요청"}',
 '{"고장부품": "클러치 ASS\'Y", "불량유형" : "작동이상", "조치내용" : "분해출문(세기정공)"}',
 '{"고장부품": "클러치 assy", "불량유형" : "불량", "조치내용" : "전자접촉기교체"}',
 '{"고장부품": "클러치 밋션", "불량유형" : "기어오일보출", "조치내용" : "ATF-3"}',
 '{"고장부품": "휨 가지센서", "불량유형" : "단선", "조치내용" : "교체"}',
 '{"고장부품": "안전1행정", "불량유형" : "타발정지위치이상", "조치내용" : "리미트캠스위치교체및조정,상사점리미트스위치교체"}',
 '{"고장부품": "QDC 클램프", "불량유형" : "기동이상", "조치내용" : "에어빼기"}',
 '{"고장부품": "피이더", "불량유형" : "소재 진입이상", "조치내용" : "캠 스위치 조정"}',
 '{"고장부품": "카운터", "불량유형" : "완료시 정지시점 불량", "조치내용" : "카운타 각도 조정"}',
 '{"고장부품": "NC FEEDER 코일", "불량유형" : "이송거리 이상", "조치내용" : "재 셋팅"}']

In [50]:
result[0]

'{"고장부품": "F/P 기능상실 PLC", "불량유형" : "클램프 감지센샤", "조치내용" : "조정"}'

In [51]:
type(result[0])

str

In [52]:
result = [ast.literal_eval(element) for element in result]
# ast.literal_eval() : 문자열로 표현(str) >> 실제 파이선 객체

result

[{'고장부품': 'F/P 기능상실 PLC', '불량유형': '클램프 감지센샤', '조치내용': '조정'},
 {'고장부품': '와이어', '불량유형': '전진동작이상', '조치내용': '점검 중 정상 작동됨'},
 {'고장부품': '클램프', '불량유형': '기동이상', '조치내용': '오일보충, 에어 제거'},
 {'고장부품': '피이더 조작판 매입 콘센트', '불량유형': '고정 불량', '조치내용': '고정'},
 {'고장부품': 'QDC', '불량유형': '파손', '조치내용': '클램프 교체'},
 {'고장부품': '광세샤 고정블록 볼트', '불량유형': '마모', '조치내용': '600ton 것으로 대체'},
 {'고장부품': '휠', '불량유형': '회전 작동불량', '조치내용': '세기정공 AS 요청'},
 {'고장부품': "클러치 ASS'Y", '불량유형': '작동이상', '조치내용': '분해출문(세기정공)'},
 {'고장부품': '클러치 assy', '불량유형': '불량', '조치내용': '전자접촉기교체'},
 {'고장부품': '클러치 밋션', '불량유형': '기어오일보출', '조치내용': 'ATF-3'},
 {'고장부품': '휨 가지센서', '불량유형': '단선', '조치내용': '교체'},
 {'고장부품': '안전1행정', '불량유형': '타발정지위치이상', '조치내용': '리미트캠스위치교체및조정,상사점리미트스위치교체'},
 {'고장부품': 'QDC 클램프', '불량유형': '기동이상', '조치내용': '에어빼기'},
 {'고장부품': '피이더', '불량유형': '소재 진입이상', '조치내용': '캠 스위치 조정'},
 {'고장부품': '카운터', '불량유형': '완료시 정지시점 불량', '조치내용': '카운타 각도 조정'},
 {'고장부품': 'NC FEEDER 코일', '불량유형': '이송거리 이상', '조치내용': '재 셋팅'}]

In [53]:
pd.DataFrame(result)

              고장부품         불량유형                      조치내용
0     F/P 기능상실 PLC     클램프 감지센샤                        조정
1              와이어       전진동작이상               점검 중 정상 작동됨
2              클램프         기동이상               오일보충, 에어 제거
3   피이더 조작판 매입 콘센트        고정 불량                        고정
4              QDC           파손                    클램프 교체
5      광세샤 고정블록 볼트           마모             600ton 것으로 대체
6                휠      회전 작동불량                세기정공 AS 요청
7        클러치 ASS'Y         작동이상                분해출문(세기정공)
8         클러치 assy           불량                   전자접촉기교체
9           클러치 밋션       기어오일보출                     ATF-3
10          휨 가지센서           단선                        교체
11           안전1행정     타발정지위치이상  리미트캠스위치교체및조정,상사점리미트스위치교체
12         QDC 클램프         기동이상                      에어빼기
13             피이더      소재 진입이상                  캠 스위치 조정
14             카운터  완료시 정지시점 불량                 카운타 각도 조정
15    NC FEEDER 코일      이송거리 이상                      재 셋팅

In [54]:
new_df = pd.DataFrame(result)

In [55]:
sub_df.head()

         수리일자                           고장내용  고장부품  불량유형  조치내용
0  2022-02-23  F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정  None  None  None
1  2022-04-06         와이어 전진동작이상 점검 중 정상 작동됨  None  None  None
2  2021-02-20             클램프기동이상 오일보충 에어 제거  None  None  None
3  2021-02-26              피이더 조작판 매입 콘센트 고정  None  None  None
4  2021-04-13                  QDC 파손 클램프 교체  None  None  None

In [56]:
print(new_df.columns)
print()
print(sub_df.columns)

Index(['고장부품', '불량유형', '조치내용'], dtype='object')

Index(['수리일자', '고장내용', '고장부품', '불량유형', '조치내용'], dtype='object')

In [57]:
sub_df['고장부품'] = new_df['고장부품']
sub_df['불량유형'] = new_df['불량유형']
sub_df['조치내용'] = new_df['조치내용']

<ipython-input-57-2e3c98d9f99a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['고장부품'] = new_df['고장부품']
<ipython-input-57-2e3c98d9f99a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['불량유형'] = new_df['불량유형']
<ipython-input-57-2e3c98d9f99a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['조치내용'] = new_df['조치내용']

In [58]:
sub_df

,수리일자,고장내용,고장부품,불량유형,조치내용
0,2022-02-23,F/P 기능상실 PLC 확인 및 클램프 감지센샤 조정,F/P 기능상실 PLC,클램프 감지센샤,조정
1,2022-04-06,와이어 전진동작이상 점검 중 정상 작동됨,와이어,전진동작이상,점검 중 정상 작동됨
2,2021-02-20,클램프기동이상 오일보충 에어 제거,클램프,기동이상,"오일보충, 에어 제거"
3,2021-02-26,피이더 조작판 매입 콘센트 고정,피이더 조작판 매입 콘센트,고정 불량,고정
4,2021-04-13,QDC 파손 클램프 교체,QDC,파손,클램프 교체
5,2021-07-30,광세샤 고정블록 볼트 마모 600ton 것으로 대체,광세샤 고정블록 볼트,마모,600ton 것으로 대체
6,2022-07-12,휠 회전 작동불량 점검 세기정공 AS 요청,휠,회전 작동불량,세기정공 AS 요청
7,2022-07-13,클러치 ASS'Y 작동이상 분해출문(세기정공),클러치 ASS'Y,작동이상,분해출문(세기정공)
8,2022-07-18,클러치 assy 불량으로 전자접촉기교체,클러치 assy,불량,전자접촉기교체
9,2022-07-18,클러치 밋션 기어오일보출 ATF-3,클러치 밋션,기어오일보출,ATF-3
10,2022-08-11,휨 가지센서 단선 교체,휨 가지센서,단선,교체
11,2022-09-13,"안전1행정 타발정지위치이상 리미트캠스위치교체및조정,상사점리미트스위치교체",안전1행정,타발정지위치이상,"리미트캠스위치교체및조정,상사점리미트스위치교체"
12,2022-10-04,QDC 클램프 기동이상 에어빼기,QDC 클램프,기동이상,에어빼기
13,2022-10-26,피이더 소재 진입이상 캠 스위치 조정,피이더,소재 진입이상,캠 스위치 조정
14,2022-11-11,카운터 완료시 정지시점 불량 카운타 각도 조정,카운터,완료시 정지시점 불량,카운타 각도 조정
15,2022-11-14,NC FEEDER 코일 이송거리 이상 재 셋팅,NC FEEDER 코일,이송거리 이상,재 셋팅

In [ ]:
sub_df.to_csv('./df_outoforder.csv', index=False)